#!/usr/bin/env bash

NIXINIT_MARKER="Auto-generated by nixinit"
CONFIG_ROOT="./configs"


function try_install() {
    { command -v "$1" >/dev/null 2>&1 && echo "$1 already installed"; } || { echo "Installing $1..." && apt install "$1"; }
}

function try_update_config() {
    src="$1" && shift
    dst="$1" && shift
    mark="$1" && shift

    if [[ ! -e $dst ]]
    then
        echo -n "Creating $dst..."
        touch $dst
        echo "done"
    fi


    if grep -qF "$mark" $dst; then
        echo "$dst already up to date"
        return 0
    fi

    echo -n "Updating $dst..."

    echo "" >> $dst
    echo $mark >> $dst
    cat $src >> $dst

    echo "done"
}


# Configs
try_update_config "$CONFIG_ROOT/bashrc" ~/.bashrc "# $NIXINIT_MARKER"
source ~/.bashrc
try_update_config "$CONFIG_ROOT/vimrc" ~/.vimrc "\" $NIXINIT_MARKER"

# Git
cp $CONFIG_ROOT/gitconfig ~/.gitconfig

# Programs
try_install sl

